package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name = "articulo", catalog = "diinventarioexamen")
public class Articulo implements java.io.Serializable {

	private int idarticulo;
	private Articulo articulo;
	private Departamento departamento;
	private Espacio espacio;
	private Modeloarticulo modeloarticulo;
	private Usuario usuarioByUsuariobaja;
	private Usuario usuarioByUsuarioalta;
	private String numserie;
	private String estado;
	private Date fechaalta;
	private Date fechabaja;
	private String observaciones;
	private Set<Salida> salidas = new HashSet<Salida>(0);
	private Set<Articulo> articulos = new HashSet<Articulo>(0);

	public Articulo() {
	}

	public Articulo(int idarticulo, Espacio espacio, Modeloarticulo modeloarticulo) {
		this.idarticulo = idarticulo;
		this.espacio = espacio;
		this.modeloarticulo = modeloarticulo;
	}

	public Articulo(int idarticulo, Articulo articulo, Departamento departamento, Espacio espacio,
			Modeloarticulo modeloarticulo, Usuario usuarioByUsuariobaja, Usuario usuarioByUsuarioalta, String numserie,
			String estado, Date fechaalta, Date fechabaja, String observaciones, Set<Salida> salidas,
			Set<Articulo> articulos) {
		this.idarticulo = idarticulo;
		this.articulo = articulo;
		this.departamento = departamento;
		this.espacio = espacio;
		this.modeloarticulo = modeloarticulo;
		this.usuarioByUsuariobaja = usuarioByUsuariobaja;
		this.usuarioByUsuarioalta = usuarioByUsuarioalta;
		this.numserie = numserie;
		this.estado = estado;
		this.fechaalta = fechaalta;
		this.fechabaja = fechabaja;
		this.observaciones = observaciones;
		this.salidas = salidas;
		this.articulos = articulos;
	}

	@Id

	@Column(name = "idarticulo", unique = true, nullable = false)
	public int getIdarticulo() {
		return this.idarticulo;
	}

	public void setIdarticulo(int idarticulo) {
		this.idarticulo = idarticulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dentrode")
	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departamento")
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "espacio", nullable = false)
	public Espacio getEspacio() {
		return this.espacio;
	}

	public void setEspacio(Espacio espacio) {
		this.espacio = espacio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo", nullable = false)
	public Modeloarticulo getModeloarticulo() {
		return this.modeloarticulo;
	}

	public void setModeloarticulo(Modeloarticulo modeloarticulo) {
		this.modeloarticulo = modeloarticulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuariobaja")
	public Usuario getUsuarioByUsuariobaja() {
		return this.usuarioByUsuariobaja;
	}

	public void setUsuarioByUsuariobaja(Usuario usuarioByUsuariobaja) {
		this.usuarioByUsuariobaja = usuarioByUsuariobaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioalta")
	public Usuario getUsuarioByUsuarioalta() {
		return this.usuarioByUsuarioalta;
	}

	public void setUsuarioByUsuarioalta(Usuario usuarioByUsuarioalta) {
		this.usuarioByUsuarioalta = usuarioByUsuarioalta;
	}

	@Column(name = "numserie", length = 45)
	public String getNumserie() {
		return this.numserie;
	}

	public void setNumserie(String numserie) {
		this.numserie = numserie;
	}

	@Column(name = "estado", length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaalta", length = 10)
	public Date getFechaalta() {
		return this.fechaalta;
	}

	public void setFechaalta(Date fechaalta) {
		this.fechaalta = fechaalta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechabaja", length = 10)
	public Date getFechabaja() {
		return this.fechabaja;
	}

	public void setFechabaja(Date fechabaja) {
		this.fechabaja = fechabaja;
	}

	@Column(name = "observaciones", length = 16777215)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "articulo")
	public Set<Salida> getSalidas() {
		return this.salidas;
	}

	public void setSalidas(Set<Salida> salidas) {
		this.salidas = salidas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "articulo")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}

}
