package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Espacio generated by hbm2java
 */
@Entity
@Table(name = "espacio", catalog = "diinventarioexamen", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Espacio implements java.io.Serializable {

	private int idespacio;
	private Espacio espacio;
	private String nombre;
	private String descripcion;
	private Set<Articulo> articulos = new HashSet<Articulo>(0);
	private Set<Espacio> espacios = new HashSet<Espacio>(0);

	public Espacio() {
	}

	public Espacio(int idespacio, String nombre) {
		this.idespacio = idespacio;
		this.nombre = nombre;
	}

	public Espacio(int idespacio, Espacio espacio, String nombre, String descripcion, Set<Articulo> articulos,
			Set<Espacio> espacios) {
		this.idespacio = idespacio;
		this.espacio = espacio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.articulos = articulos;
		this.espacios = espacios;
	}

	@Id

	@Column(name = "idespacio", unique = true, nullable = false)
	public int getIdespacio() {
		return this.idespacio;
	}

	public void setIdespacio(int idespacio) {
		this.idespacio = idespacio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "padre")
	public Espacio getEspacio() {
		return this.espacio;
	}

	public void setEspacio(Espacio espacio) {
		this.espacio = espacio;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 15)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "espacio")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "espacio")
	public Set<Espacio> getEspacios() {
		return this.espacios;
	}

	public void setEspacios(Set<Espacio> espacios) {
		this.espacios = espacios;
	}

}
