package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ficherousuario generated by hbm2java
 */
@Entity
@Table(name = "ficherousuario", catalog = "diinventarioexamen")
public class Ficherousuario implements java.io.Serializable {

	private int idficherousuario;
	private Usuario usuario;
	private String tipo;
	private String nombre;
	private byte[] contenido;

	public Ficherousuario() {
	}

	public Ficherousuario(int idficherousuario, Usuario usuario) {
		this.idficherousuario = idficherousuario;
		this.usuario = usuario;
	}

	public Ficherousuario(int idficherousuario, Usuario usuario, String tipo, String nombre, byte[] contenido) {
		this.idficherousuario = idficherousuario;
		this.usuario = usuario;
		this.tipo = tipo;
		this.nombre = nombre;
		this.contenido = contenido;
	}

	@Id

	@Column(name = "idficherousuario", unique = true, nullable = false)
	public int getIdficherousuario() {
		return this.idficherousuario;
	}

	public void setIdficherousuario(int idficherousuario) {
		this.idficherousuario = idficherousuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "tipo", length = 45)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "contenido")
	public byte[] getContenido() {
		return this.contenido;
	}

	public void setContenido(byte[] contenido) {
		this.contenido = contenido;
	}

}
