package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ficheromodelo generated by hbm2java
 */
@Entity
@Table(name = "ficheromodelo", catalog = "diinventarioexamen")
public class Ficheromodelo implements java.io.Serializable {

	private int idficheromodelo;
	private Modeloarticulo modeloarticulo;
	private String nombre;
	private String tipo;
	private byte[] contenido;

	public Ficheromodelo() {
	}

	public Ficheromodelo(int idficheromodelo, Modeloarticulo modeloarticulo) {
		this.idficheromodelo = idficheromodelo;
		this.modeloarticulo = modeloarticulo;
	}

	public Ficheromodelo(int idficheromodelo, Modeloarticulo modeloarticulo, String nombre, String tipo,
			byte[] contenido) {
		this.idficheromodelo = idficheromodelo;
		this.modeloarticulo = modeloarticulo;
		this.nombre = nombre;
		this.tipo = tipo;
		this.contenido = contenido;
	}

	@Id

	@Column(name = "idficheromodelo", unique = true, nullable = false)
	public int getIdficheromodelo() {
		return this.idficheromodelo;
	}

	public void setIdficheromodelo(int idficheromodelo) {
		this.idficheromodelo = idficheromodelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo", nullable = false)
	public Modeloarticulo getModeloarticulo() {
		return this.modeloarticulo;
	}

	public void setModeloarticulo(Modeloarticulo modeloarticulo) {
		this.modeloarticulo = modeloarticulo;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo", length = 45)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "contenido")
	public byte[] getContenido() {
		return this.contenido;
	}

	public void setContenido(byte[] contenido) {
		this.contenido = contenido;
	}

}
