package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "grupo", catalog = "diinventarioexamen", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Grupo implements java.io.Serializable {

	private String idgrupo;
	private String nombre;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Grupo() {
	}

	public Grupo(String idgrupo, String nombre) {
		this.idgrupo = idgrupo;
		this.nombre = nombre;
	}

	public Grupo(String idgrupo, String nombre, Set<Usuario> usuarios) {
		this.idgrupo = idgrupo;
		this.nombre = nombre;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "idgrupo", unique = true, nullable = false, length = 10)
	public String getIdgrupo() {
		return this.idgrupo;
	}

	public void setIdgrupo(String idgrupo) {
		this.idgrupo = idgrupo;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
