package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name = "permiso", catalog = "diinventarioexamen", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Permiso implements java.io.Serializable {

	private Integer idpermiso;
	private Permiso permiso;
	private String nombre;
	private String descripcion;
	private Set<Permiso> permisos = new HashSet<Permiso>(0);
	private Set<Permisosrol> permisosrols = new HashSet<Permisosrol>(0);

	public Permiso() {
	}

	public Permiso(String nombre) {
		this.nombre = nombre;
	}

	public Permiso(Permiso permiso, String nombre, String descripcion, Set<Permiso> permisos,
			Set<Permisosrol> permisosrols) {
		this.permiso = permiso;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.permisos = permisos;
		this.permisosrols = permisosrols;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpermiso", unique = true, nullable = false)
	public Integer getIdpermiso() {
		return this.idpermiso;
	}

	public void setIdpermiso(Integer idpermiso) {
		this.idpermiso = idpermiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permisopadre")
	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permiso")
	public Set<Permiso> getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permiso")
	public Set<Permisosrol> getPermisosrols() {
		return this.permisosrols;
	}

	public void setPermisosrols(Set<Permisosrol> permisosrols) {
		this.permisosrols = permisosrols;
	}

}
