package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "diinventarioexamen", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Rol implements java.io.Serializable {

	private Integer idrol;
	private String nombre;
	private String descripcion;
	private Set<Permisosrol> permisosrols = new HashSet<Permisosrol>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Rol() {
	}

	public Rol(String nombre) {
		this.nombre = nombre;
	}

	public Rol(String nombre, String descripcion, Set<Permisosrol> permisosrols, Set<Usuario> usuarios) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.permisosrols = permisosrols;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idrol", unique = true, nullable = false)
	public Integer getIdrol() {
		return this.idrol;
	}

	public void setIdrol(Integer idrol) {
		this.idrol = idrol;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Permisosrol> getPermisosrols() {
		return this.permisosrols;
	}

	public void setPermisosrols(Set<Permisosrol> permisosrols) {
		this.permisosrols = permisosrols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
