package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salida generated by hbm2java
 */
@Entity
@Table(name = "salida", catalog = "diinventarioexamen")
public class Salida implements java.io.Serializable {

	private Integer idsalida;
	private Articulo articulo;
	private Usuario usuario;
	private Date fechasalida;
	private Date fechadevolucion;

	public Salida() {
	}

	public Salida(Articulo articulo, Usuario usuario, Date fechasalida) {
		this.articulo = articulo;
		this.usuario = usuario;
		this.fechasalida = fechasalida;
	}

	public Salida(Articulo articulo, Usuario usuario, Date fechasalida, Date fechadevolucion) {
		this.articulo = articulo;
		this.usuario = usuario;
		this.fechasalida = fechasalida;
		this.fechadevolucion = fechadevolucion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsalida", unique = true, nullable = false)
	public Integer getIdsalida() {
		return this.idsalida;
	}

	public void setIdsalida(Integer idsalida) {
		this.idsalida = idsalida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "articulo", nullable = false)
	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechasalida", nullable = false, length = 19)
	public Date getFechasalida() {
		return this.fechasalida;
	}

	public void setFechasalida(Date fechasalida) {
		this.fechasalida = fechasalida;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechadevolucion", length = 19)
	public Date getFechadevolucion() {
		return this.fechadevolucion;
	}

	public void setFechadevolucion(Date fechadevolucion) {
		this.fechadevolucion = fechadevolucion;
	}

}
