package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tipousuario generated by hbm2java
 */
@Entity
@Table(name = "tipousuario", catalog = "diinventarioexamen", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Tipousuario implements java.io.Serializable {

	private Integer idtipousuario;
	private String nombre;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Tipousuario() {
	}

	public Tipousuario(String nombre, Set<Usuario> usuarios) {
		this.nombre = nombre;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipousuario", unique = true, nullable = false)
	public Integer getIdtipousuario() {
		return this.idtipousuario;
	}

	public void setIdtipousuario(Integer idtipousuario) {
		this.idtipousuario = idtipousuario;
	}

	@Column(name = "nombre", unique = true, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipousuario")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
