package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "diinventarioexamen", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private Departamento departamento;
	private Grupo grupo;
	private Rol rol;
	private Tipousuario tipousuario;
	private String username;
	private String password;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String domicilio;
	private String poblacion;
	private String codpostal;
	private String email;
	private String telefono;
	private Set<Ficherousuario> ficherousuarios = new HashSet<Ficherousuario>(0);
	private Set<Salida> salidas = new HashSet<Salida>(0);
	private Set<Articulo> articulosForUsuariobaja = new HashSet<Articulo>(0);
	private Set<Articulo> articulosForUsuarioalta = new HashSet<Articulo>(0);

	public Usuario() {
	}

	public Usuario(Rol rol, Tipousuario tipousuario, String username, String password) {
		this.rol = rol;
		this.tipousuario = tipousuario;
		this.username = username;
		this.password = password;
	}

	public Usuario(Departamento departamento, Grupo grupo, Rol rol, Tipousuario tipousuario, String username,
			String password, String nombre, String apellido1, String apellido2, String domicilio, String poblacion,
			String codpostal, String email, String telefono, Set<Ficherousuario> ficherousuarios, Set<Salida> salidas,
			Set<Articulo> articulosForUsuariobaja, Set<Articulo> articulosForUsuarioalta) {
		this.departamento = departamento;
		this.grupo = grupo;
		this.rol = rol;
		this.tipousuario = tipousuario;
		this.username = username;
		this.password = password;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.domicilio = domicilio;
		this.poblacion = poblacion;
		this.codpostal = codpostal;
		this.email = email;
		this.telefono = telefono;
		this.ficherousuarios = ficherousuarios;
		this.salidas = salidas;
		this.articulosForUsuariobaja = articulosForUsuariobaja;
		this.articulosForUsuarioalta = articulosForUsuarioalta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idusuario", unique = true, nullable = false)
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departamento")
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grupo")
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo", nullable = false)
	public Tipousuario getTipousuario() {
		return this.tipousuario;
	}

	public void setTipousuario(Tipousuario tipousuario) {
		this.tipousuario = tipousuario;
	}

	@Column(name = "username", unique = true, nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", length = 45)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 45)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "domicilio", length = 45)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@Column(name = "poblacion", length = 45)
	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	@Column(name = "codpostal", length = 10)
	public String getCodpostal() {
		return this.codpostal;
	}

	public void setCodpostal(String codpostal) {
		this.codpostal = codpostal;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Ficherousuario> getFicherousuarios() {
		return this.ficherousuarios;
	}

	public void setFicherousuarios(Set<Ficherousuario> ficherousuarios) {
		this.ficherousuarios = ficherousuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Salida> getSalidas() {
		return this.salidas;
	}

	public void setSalidas(Set<Salida> salidas) {
		this.salidas = salidas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioByUsuariobaja")
	public Set<Articulo> getArticulosForUsuariobaja() {
		return this.articulosForUsuariobaja;
	}

	public void setArticulosForUsuariobaja(Set<Articulo> articulosForUsuariobaja) {
		this.articulosForUsuariobaja = articulosForUsuariobaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioByUsuarioalta")
	public Set<Articulo> getArticulosForUsuarioalta() {
		return this.articulosForUsuarioalta;
	}

	public void setArticulosForUsuarioalta(Set<Articulo> articulosForUsuarioalta) {
		this.articulosForUsuarioalta = articulosForUsuarioalta;
	}

}
