package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modeloarticulo generated by hbm2java
 */
@Entity
@Table(name = "modeloarticulo", catalog = "diinventarioexamen")
public class Modeloarticulo implements java.io.Serializable {

	private Integer idmodeloarticulo;
	private Tipoarticulo tipoarticulo;
	private String nombre;
	private String descripcion;
	private String marca;
	private String modelo;
	private Set<Articulo> articulos = new HashSet<Articulo>(0);
	private Set<Ficheromodelo> ficheromodelos = new HashSet<Ficheromodelo>(0);

	public Modeloarticulo() {
	}

	public Modeloarticulo(Tipoarticulo tipoarticulo, String nombre, String descripcion, String marca, String modelo,
			Set<Articulo> articulos, Set<Ficheromodelo> ficheromodelos) {
		this.tipoarticulo = tipoarticulo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.marca = marca;
		this.modelo = modelo;
		this.articulos = articulos;
		this.ficheromodelos = ficheromodelos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmodeloarticulo", unique = true, nullable = false)
	public Integer getIdmodeloarticulo() {
		return this.idmodeloarticulo;
	}

	public void setIdmodeloarticulo(Integer idmodeloarticulo) {
		this.idmodeloarticulo = idmodeloarticulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo")
	public Tipoarticulo getTipoarticulo() {
		return this.tipoarticulo;
	}

	public void setTipoarticulo(Tipoarticulo tipoarticulo) {
		this.tipoarticulo = tipoarticulo;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 16777215)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "marca")
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "modelo")
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloarticulo")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloarticulo")
	public Set<Ficheromodelo> getFicheromodelos() {
		return this.ficheromodelos;
	}

	public void setFicheromodelos(Set<Ficheromodelo> ficheromodelos) {
		this.ficheromodelos = ficheromodelos;
	}

}
