package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permisosrol generated by hbm2java
 */
@Entity
@Table(name = "permisosrol", catalog = "diinventarioexamen")
public class Permisosrol implements java.io.Serializable {

	private int idpermisosrol;
	private Permiso permiso;
	private Rol rol;
	private Integer acceso;

	public Permisosrol() {
	}

	public Permisosrol(int idpermisosrol, Permiso permiso, Rol rol) {
		this.idpermisosrol = idpermisosrol;
		this.permiso = permiso;
		this.rol = rol;
	}

	public Permisosrol(int idpermisosrol, Permiso permiso, Rol rol, Integer acceso) {
		this.idpermisosrol = idpermisosrol;
		this.permiso = permiso;
		this.rol = rol;
		this.acceso = acceso;
	}

	@Id

	@Column(name = "idpermisosrol", unique = true, nullable = false)
	public int getIdpermisosrol() {
		return this.idpermisosrol;
	}

	public void setIdpermisosrol(int idpermisosrol) {
		this.idpermisosrol = idpermisosrol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permiso", nullable = false)
	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "acceso")
	public Integer getAcceso() {
		return this.acceso;
	}

	public void setAcceso(Integer acceso) {
		this.acceso = acceso;
	}

}
