package pojos;
// Generated 17 de febr. 2025, 13:37:17 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoarticulo generated by hbm2java
 */
@Entity
@Table(name = "tipoarticulo", catalog = "diinventarioexamen")
public class Tipoarticulo implements java.io.Serializable {

	private Integer idtipoarticulo;
	private Tipoarticulo tipoarticulo;
	private String nombre;
	private Set<Modeloarticulo> modeloarticulos = new HashSet<Modeloarticulo>(0);
	private Set<Tipoarticulo> tipoarticulos = new HashSet<Tipoarticulo>(0);

	public Tipoarticulo() {
	}

	public Tipoarticulo(String nombre) {
		this.nombre = nombre;
	}

	public Tipoarticulo(Tipoarticulo tipoarticulo, String nombre, Set<Modeloarticulo> modeloarticulos,
			Set<Tipoarticulo> tipoarticulos) {
		this.tipoarticulo = tipoarticulo;
		this.nombre = nombre;
		this.modeloarticulos = modeloarticulos;
		this.tipoarticulos = tipoarticulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipoarticulo", unique = true, nullable = false)
	public Integer getIdtipoarticulo() {
		return this.idtipoarticulo;
	}

	public void setIdtipoarticulo(Integer idtipoarticulo) {
		this.idtipoarticulo = idtipoarticulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "padre")
	public Tipoarticulo getTipoarticulo() {
		return this.tipoarticulo;
	}

	public void setTipoarticulo(Tipoarticulo tipoarticulo) {
		this.tipoarticulo = tipoarticulo;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoarticulo")
	public Set<Modeloarticulo> getModeloarticulos() {
		return this.modeloarticulos;
	}

	public void setModeloarticulos(Set<Modeloarticulo> modeloarticulos) {
		this.modeloarticulos = modeloarticulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoarticulo")
	public Set<Tipoarticulo> getTipoarticulos() {
		return this.tipoarticulos;
	}

	public void setTipoarticulos(Set<Tipoarticulo> tipoarticulos) {
		this.tipoarticulos = tipoarticulos;
	}

}
